# Generated by Django 2.1.1 on 2018-09-14 00:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('goods_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('lastbid_username', models.CharField(max_length=20, null=True)),
                ('lastbid_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('goods_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('highest_price', models.PositiveIntegerField(default=django.db.models.fields.PositiveIntegerField)),
            ],
        ),
        migrations.CreateModel(
            name='RoleofUser',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('nickname', models.CharField(default=models.CharField(max_length=20, primary_key=True, serialize=False), max_length=20)),
                ('assets', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
    ]
