# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('G_number', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=30)),
                ('minimum_price', models.PositiveIntegerField()),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('review', 'WaitingforReview'), ('in', 'inAuction'), ('end', 'endAuction')], default='review', max_length=6)),
                ('lastbid_username', models.CharField(max_length=20, null=True)),
                ('lastbid_time', models.DateTimeField(null=True)),
                ('lastprice', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('sourceName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sourceIP', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('nickname', models.CharField(default='none', max_length=20)),
                ('assets', models.PositiveIntegerField(default=0)),
                ('isAdministrator', models.CharField(choices=[('0', 'not_administrator'), ('1', 'goods_administrator')], default='0', max_length=20)),
                ('isGeneralUser', models.CharField(choices=[('0', 'not_general_user'), ('1', 'general_user')], default='1', max_length=20)),
                ('status', models.CharField(choices=[('0', 'normal'), ('1', 'banned')], default='0', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='privatechat',
            name='targetName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User'),
        ),
    ]
