# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20180917_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='targetName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User'),
        ),
    ]
