# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20180917_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleofUser',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GU', 'general_user'), ('GA', 'goods_administrator')], default='GU', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='targetName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User'),
        ),
    ]
